# Generated by Django 4.1.6 on 2023-02-15 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('points', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busAllowed', models.BooleanField()),
                ('carAllowed', models.BooleanField()),
                ('subwayAllowed', models.BooleanField()),
                ('boatAllowed', models.BooleanField()),
                ('radius', models.PositiveIntegerField()),
                ('intendedCompletionTime', models.PositiveIntegerField()),
                ('theme', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=13, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField()),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('maxTime', models.IntegerField()),
                ('numFinished', models.IntegerField()),
                ('destinations', models.ManyToManyField(to='townie_app.destination')),
                ('members', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='townie_app.group')),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='townie_app.gamesettings')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='townie_app.location'),
        ),
    ]
